---
output: 
  github_document:
    toc: true
---

# Exercícios para quinta-feira

A ideia para esse exercício é praticar os conceitos vistos nas aulas 1 e 2.

Caso você não tenha feito o exercício da aula 1, as instruções estão abaixo:

## Prática - Exercício 1

Considerando as enquetes no site da Câmara dos deputados:
https://www.camara.leg.br/enquetes/

Escolha outra enquete de interesse (diferente da utilizada na aula, e de preferência que tenha respostas para conseguirmos analisar), e tente explorar os conceitos vistos na parte de pré-processamento usando esses dados.


Anote as dúvidas. 

## Prática - Exercício 2

Agora, o objetivo é fazer uma análise exploratória dos dados que você escolheu, e preparou. Tente pensar em possibilidades de exploração e visualização de dados além das que foram feitas em aula.

Os tópicos abaixo são sugestões de análise, mas você pode fazer outras análises que achar interessante:

- Faça uma análise exploratória dos dados, usando os conceitos vistos na aula 2. Quais são os stems mais frequentes por posicionamento?

- Faça uma visualização dos dados, usando o gráfico de barras, considerando o posicionamento.

- Faça uma visualização dos dados, usando a wordcloud, por posicionamento.


Anote as dúvidas. 
